FROM golang:1.22.4 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY ./ ./

RUN go test ./...

RUN GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=0 go build

FROM alpine:3.19.1

COPY --from=builder /app/starlink-statsd /bin/starlink-statsd
WORKDIR /var/lib/starlink-statsd/

CMD ["/bin/starlink-statsd"]
