FROM golang:1.18.1 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY ./ ./

RUN go test ./...

RUN GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=0 go build

FROM alpine:3.16.2

COPY --from=builder /app/ecowitt-statsd /bin/ecowitt-statsd
WORKDIR /var/lib/ecowitt-statsd/

CMD ["/bin/ecowitt-statsd"]
